### ISSUE TITLE
Optional chaining

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template#134]
How to use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) with this amazing template?

**Comment by Conduitry** [comment]
https://github.com/sveltejs/svelte/issues/1972

**Comment by mvolkmann** [comment]
Why was this issue closed? As far as I can tell, with the latest version of Svelte we can use optional chaining and nullish coalescing when `npm run dev` is used, but it fails with `npm run build` because Terser doesn't support it yet. It seems to me that until that is fixed, sveltejs/template can't claim to support those JS features.

**Comment by benmccann** [comment]
Here's the terser issue to track for reference: https://github.com/terser/terser/issues/567
