### ISSUE TITLE
Use dependabot to update dependencies

### ISSUE THREAD

**Issue by SagnikPradhan** [sveltejs/template#141]
Add [this](https://github.com/marketplace/dependabot-preview) to the repository, will prevent outdated dependencies.

**Comment by Conduitry** [comment]
This repository specifically does not have a dependency lockfile. We don't need to be continually updating the package.json to point to the latest versions, since users will automatically get those anyway when they install. The only time users won't get the latest versions is when there's been a major version bump, which dependabot wouldn't be able to help us with anyway, as it will involve manual inspection of the breaking changes to see how they affect us.

**Comment by SagnikPradhan** [comment]
Alright. Asked cause the `plugin-serve` branch hasn't been updated since a long time. Uses deprecated packages.

**Comment by antony** [comment]
That branch isn't in use, it's just an old branch. It probably needs to be deleted.

**Comment by antony** [comment]
Was a leftover artifact from https://github.com/sveltejs/template/pull/87 - deleted.
