### ISSUE TITLE
Obsolete option to the Svelte plugin in the Rollup config

### ISSUE THREAD

**Issue by illright** [sveltejs/template#180]
https://github.com/sveltejs/template/blob/master/rollup.config.js#L41

The template passes a `dev` option to the `svelte()` plugin of Rollup which doesn't seem to exist (any more?)

**Comment by lukeed** [comment]
The `master` branch `rollup-plugin-svelte` is unreleased. There are breaking changes there, which happen to include removing of the `dev` option.

Please look at the [`6.x`](https://www.npmjs.com/package/rollup-plugin-svelte/v/6.1.0) release for documentation, since that's the version that this template is using. It may be the case that Intellisense says `dev` is an invalid option, but that's a TypeScript definitions issue. This template is still current/up-to-date.

Thanks!

**Comment by aabounegm** [comment]
Actually, I cannot find the `dev` option even in the link you shared for the `6.x` release. In fact, the word "dev" does not exist in the [source code](https://github.com/sveltejs/rollup-plugin-svelte/blob/6.x/index.js) of the `6.x` release or [its typings](https://github.com/sveltejs/rollup-plugin-svelte/blob/6.x/index.d.ts).
If the option somehow gets passed to the compiler implicitly, shouldn't that be reflected on the typings?

**Comment by lukeed** [comment]
Yes. You can open a PR to that `6.x` branch if you like.

This PR (https://github.com/sveltejs/rollup-plugin-svelte/pull/126) was added to directly expose the `svelte/compiler` types & avoid problems like this – but it required a `peerDependency` restraint on svelte > 3.5, so it will be part of the upcoming 7.0 release.
