### ISSUE TITLE
Intended TypeScript workflow question

### ISSUE THREAD

**Issue by lpil** [sveltejs/template#215]
Hello! Thank you for this excellent template, it is very useful and I'm really enjoying it.

I had a question on the intended way to use it with TypeScript: When there is a type error the rollup bundler does not print the error and the build succeeds.

I understand this means the build is faster, which is great, but what is the intended way for these type errors to be surfaced as they are not in the console? I see there is a `npm run validate` command but there is no command for the watching version, so I was unsure if this was to be used in development or just on CI.

Thank you,
Louis

**Comment by dummdidumm** [comment]
Svelte's script contents cannot be looked at in isolation, passing this to TypeScript would lead to incomplete or even wrong diagnostics. That's why we have a dedicated tool called `svelte-check` which does the job of translating the Svelte code to something TypeScript can properly check. It's also the tool that's used when you do `npm run validate`.

To answer your question: `svelte-check` also has a watch mode, just add `--watch` as a option parameter. You could add this to your `package.json`'s scripts: `"validate:watch": "svelte-check --watch"`. For more, see this README: https://www.npmjs.com/package/svelte-check

**Comment by lpil** [comment]
Thank you
