### ISSUE TITLE
Linters for template

### ISSUE THREAD

**Issue by popuguytheparrot** [sveltejs/template#27]
What do you think about the linter configuration in the template?
For example for eslint and prettier.
Using a template, I would not want to have a cognitive load when installing plugins for linter etc

**Comment by antony** [comment]
Rich has some quite strong opinions about code style which are quite opposite to the general opinons on code style.

Personally I wouldn't want to see Svelte biased in either direction, as code style is a very personal choice, and is often the source of some very lengthy bikeshedding.

**Comment by popuguytheparrot** [comment]
@antony 
For example, in the React when installing the with `create-react-app` set the rules for linter. I would like to have the same in the template (eslint-plugin-svelte3)

**Comment by pngwn** [comment]
Mybe we could have a 'bare-bones' template with just enough to create a svelte component and nothing else and a 'with-tooling' with stuff like linting, test boilerplate (when we work that out). Rather than supporting a million configuations.

The linting config provided would need some discussion, however.
