### ISSUE TITLE
Vulnerability found in ws dependency

### ISSUE THREAD

**Issue by mgmarlow** [sveltejs/template#52]
Just bootstrapped a new svelte project using this template and pushed it to Github. Github now notifies me with a vulnerability warning for the dependency **ws**. The dependency belongs to `rollup-plugin-livereload#livereload`, as shown with `yarn why ws`.

There's an open ticket in livereload to address this vulnerability: https://github.com/napcs/node-livereload/issues/130. Yet I still opened this ticket to bring visibility.

![image](https://user-images.githubusercontent.com/3778552/60680506-72a4a880-9e40-11e9-9e13-268f9bc8b667.png)

```
yarn why ws
=> Found "ws@1.1.5"
info Reasons this module exists
   - "rollup-plugin-livereload#livereload" depends on it
   - Hoisted from "rollup-plugin-livereload#livereload#ws"
```

**Comment by mrkishi** [comment]
Thanks for the heads up!

It seems this specific Github security alert is being erroneously reported for `ws@1.1.5`, according [npm's advisory](https://www.npmjs.com/advisories/550/versions) and [a conversation on the fix confirming the advisory's versions](https://github.com/websockets/ws/commit/c4fe46608acd61fbf7397eadc47378903f95b78a#commitcomment-28951427).

I don't think there's anything to be done here other than leaving this open for visibility until `livereload` upgrades the `ws` dependency. Since `livereload` is only used during development, production builds wouldn't be affected anyway.
