### ISSUE TITLE
Unexpected token < with default template

### ISSUE THREAD

**Issue by MontoyaAndres** [sveltejs/template#56]
I haven't added any logic to the app, it's just this template. I tried to run it with `yarn start:dev`, which is `sirv public --single --dev`.

[This is](https://github.com/MontoyaAndres/javascript-awesome-stuff/tree/master/english-sena-project) the project that I'm trying to implement. I don't know if is my Operative System or Node version, which are:

- Node: v10.16.3
- Npm: 6.9.0
- Linux: Linux Mint 19.1 Tessa

Error:

![Screenshot_2019-08-18_21-41-52](https://user-images.githubusercontent.com/15065852/63235872-08ce3b80-c201-11e9-9a2a-62a3550a2735.png)

Output from the console when loads the page:

![Screenshot_2019-08-18_21-42-42](https://user-images.githubusercontent.com/15065852/63235889-1f749280-c201-11e9-9545-9120f6b6c331.png)

Also, I tried running the `build` command and then the `start:dev` and it did not work

**Comment by subz390** [comment]
**Quick-Fix:** The app needs building first, there's no bundle files.

**Details:**  
`/bundle.js` is requested via the `<script` tag by the browser, however instead of a `404 not found` [sirv](https://github.com/lukeed/sirv) serves the root `/index.html` file instead (why?).  The browser, thinking it's JavaScript (as it's loaded via a `<script` tag) throws a `SyntaxError` at the opening `<` bracket.  Looking at the network tab, it's the correct type for html `Content-Type: text/html` though.
![190819 bundlejs](https://user-images.githubusercontent.com/11546815/63239078-5ec2d380-c241-11e9-828c-f10826348582.png)

**Comment by MontoyaAndres** [comment]
Thank you!
