### ISSUE TITLE
Browser doesn't pick up code changes

### ISSUE THREAD

**Issue by rlaferla** [sveltejs/template#77]
Description:

Browser is somehow caching the bundle.js.  In Chrome dev tools, when I click on a .svelte class in an error message, it shows me an older version of the class.  

Environment:

Browser: Chrome 77.0.3865.120 (Official Build) (64-bit)
OS:  macOS Mojave 10.14.6 (18G103)

I am using the "dev" target for yarn/npm:

    "dev": "run-p start:dev autobuild",

Severity:

This is blocking my development w/Svelte.

**Comment by oren** [comment]
I am having the same issue on Firefox 70.0 (64-bit) on Ubuntu. I even disabled `browser.cache.disk.enable` and `browser.cache.memory.enable` but I am not seeing my updates. The browser update itself only after the first code change. Any other change is being ignored and I have to rerun `npm run dev'.

**Comment by oren** [comment]
I just tested on Firefox incognito mode and the issue persist.

**Comment by oren** [comment]
Update: it's not the browser since the console doesn't change at all. Not sure how to troubleshoot this from here.

**Comment by oren** [comment]
This solved it for me:
```
 watch: {
    chokidar: false
  },
```
(based on https://github.com/rollup/rollup/issues/1666#issuecomment-372383550)

**Comment by Da2software** [comment]
In my case using Chrome, I usually add changes to my styles using the inspector to see quick changes before being added into my code, then this makes the browser save a **cache file**, that was the reason why my css changes didn't update.
I **solved** disabling this option in the inspector **Settings**:
![image](https://user-images.githubusercontent.com/32003485/127281647-22fc22d0-d7f4-4bad-8436-b57ab3725156.png)

**Comment by mikkokaar** [comment]
Experiencing a similar problem while doing dev work in a docker container -- I'd assume this has nothing to do with the browser or livereload.

Sometimes if I make changes to a frontend file (.svelte) it won't update. I delete the bundle files and grep around looking for a string I knew was in the earlier version of the file -- can't find it anywhere and I know I've changed it in the source file
 so that's to be expected. If I then spin up the dev server again (i.e. yarn dev, i.e. rollup -c -w, with rollup config being pretty much the default from the get started template) that old crap shows up in the bundle files again and the new version of the file will not end up there with any amount of saving even if the dev server notices that file changing and tries to reload.

**What helps is killing the container and starting it up again.**

I'm on macOS Big Sur using Docker Desktop, and mount the project directory into the container. Basically could be a file sharing problem, except that I can see the correct version of the file inside the container using other tools (grep, cat, etc)

Perhaps there's a cache somewhere, outside of the project directory? Couldn't find it though.
